config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :posts
  resources :profiles
  root 'posts#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       else
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Paperclip::Glue
  validates :title , presence: true , length: {minimum: 5}
  validates :body ,presence: true
  has_attached_file :post_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "missing_post.png"
  validates_attachment_content_type :post_image, :content_type => /\Aimage\/.*\Z/
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from CanCan: :AccessDenied do |exception|
    redirect_to root_path , :alert => exception.message
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all.order('created_at DESC')
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create

    @post = current_user.posts.create(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end

  end

  def edit
  end


  def update
      @post.update(post_params)
        redirect_to root_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end
  private
    def post_params
      params.require(:post).permit(:title, :body, :post_image)
    end
    def set_post
      @post = Post.find(params[:id])
    end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show]
  def show
  end
  private
    def set_profile
      @user = User.find(params[:id])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController


  def sign_up_params
    devise_parameter_sanitizer.sanitize(:sign_up)
  end

  def account_update_params
    devise_parameter_sanitizer.sanitize(:account_update)
  end

  private

  def sign_up_params
    params.require(:user).permit(:name, :surname, :email, :password, :password_confirmation, :avatar)
  end

  def account_update_params
    params.require(:user).permit(:name, :surname, :email, :password, :password_confirmation, :current_password, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
    <body>
        <div id="sidebar">
          <div id="logo">
            <%= link_to root_path do %>
                <%= image_tag "logo.png" %>
            <% end %>
          </div>
          <% if current_user %>
                <%= image_tag current_user.avatar.url(:medium), class: "sidebar_circle" %>
          <% end %>
          <ul>
            <% if current_user %>
              <li class="category"><%= current_user.name %> <%= current_user.surname %></li>
            <% end %>
              <li><%= link_to 'Home' , root_path %></li>
            <% if current_user %>
              <li><%= link_to 'Profile', profile_path(current_user) %></li>
                  <li>
                    <%= link_to 'Settings', edit_user_registration_path(@user) %>
                  </li>
              <% end %>
        </ul>
        <ul>
          <li class="category">For Developers</li>
          <li><a href="https://github.com/goktuggoktas/LYK-2015-Journal">Github</a></li>
        </ul>
          <p class="sign_in">Admin login</p>
    </div>
        <div id="main_content">
          <div id="header">
            <p>All Posts
                <% flash.each do |name,msg| %>
                    <%= content_tag(:p, msg) %>
                <% end  %>
            </p>

            <div class="buttons">
              <% if current_user %>
                  <%= link_to destroy_user_session_path , method: :delete do %>
                        <button class="button">Log out</button>
                  <% end %>
                  <%= link_to new_post_path do %>
                      <button class="button">New Post</button>
                  <% end %>
              <% else %>
                  <%= link_to new_user_session_path do %>
                      <button class="button">Sign In</button>
                  <% end %>
                  <%= link_to new_user_registration_path do %>
                      <button class="button">Sign Up</button>
                  <% end %>
              <% end %>
            </div>
          </div>
        <%= yield %>
        </div>
    </body>
</html>

app/views/posts/_form.html.erb
 <%= form_for(@post,  url: posts_path )  do |f| %>
      <% if @post.errors.any? %>
          <div id="errors"><h2><%= pluralize(@post.errors.count, 'Error') %></h2>
            <ul>
              <% @post.errors.full_messages.each do|msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <p>
        <%= f.label :title%><br>
        <%= f.text_field :title %>
      </p>
      <p>
        <%= f.label :body  %><br>
        <%= f.text_area :body %>
      </p>
      <p><%= f.file_field :post_image %></p>
      <p> <%= f.submit %></p>
  <% end  %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
  <h1>Edit Post</h1>
  <%= form_for @post,:url => post_path, method: :put, :html => { :multipart => true } do |f| %>
      <% if @post.errors.any? %>
          <div id="errors"><h2><%= pluralize(@post.errors.count, 'Error') %></h2>
            <ul>
              <% @post.errors.full_messages.each do|msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <p>
        <%= f.label :title%><br>
        <%= f.text_field :title %>
      </p>
      <p>
        <%= f.label :body  %><br>
        <%= f.text_area :body %>
      </p>
      <p><%= f.file_field :post_image %></p>
      <p> <%= f.submit %></p>
  <% end  %>

</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<div class="post_wrapper">
  <%= link_to profile_path(post.user) do %>
      <%= image_tag post.user.avatar.url(:medium) , class: "poster_photo"%>
      <div class="top_poster">
        <%= post.user.name.capitalize %>
        <%= post.user.surname.capitalize %>
  <% end %>
    Submitted <%= time_ago_in_words(post.created_at) %> Ago
  </div>
  <h4 class="title"><strong><%= link_to post.title.capitalize ,post%></strong></h4>
  <div style="padding: 0px 0px 0px 30px;">
    <div class="img-circle">
        <%= image_tag post.post_image.url(:medium) , class: "circle"%>
    </div>
    <div class="body">
      <% if post.body.length > 250%>
          <%= truncate(post.body, length: 250) %>
          <a><%= link_to 'Read more', post_path(post) %></a>

      <% else %>
          <%= post.body %>

      <% end %>


    </div>
  </div>
</div>
<% end  %>

app/views/posts/new.html.erb
<div id="page_wrapper">
  <h1>New Post</h1>

<%= render 'form' %>
    </div>

app/views/posts/show.html.erb
    <div id="post_content">
        <h1 class="title">
          <%= @post.title %>
        </h1>
        <p class="date">
          Submitted <%= time_ago_in_words(@post.created_at) %> Ago
          <% if current_user == @post.user %>
              | <%= link_to 'Edit', edit_post_path %>
              | <%= link_to 'Delete', post_path(@post) , method: :delete, data: {confirm: 'Are you sure?'} %>
              </p>
          <% end %>
          <div style="float: left;">
            <%= image_tag @post.post_image.url(:medium), class: "photo"%>
          </div>
        <p class="body"><%= @post.body %></p>
          From:
          <%= link_to profile_path(@post.user) do %>
              <%= @post.user.name.capitalize %>
              <%= @post.user.surname.upcase %>
          <% end %>
    </div>

app/views/profiles/show.html.erb
<% @user.posts.each do |post| %>
    <div class="post_wrapper">
      <h4 class="title"><strong><%= link_to post.title.capitalize ,post%></strong></h4>
      <div style="padding: 0px 0px 0px 50px;">
        <div class="img-circle">
          <%= image_tag post.post_image.url(:medium) , class: "circle"%>
        </div>
        <div class="body">
          <% if post.body.length > 250 %>
              <%= truncate(post.body, length: 250) %>
              <a><%= link_to 'Read more', post_path(post) %></a>
          <% else %>
              <%= post.body %>
          <% end %>
        </div>
      </div>
      <p class="date">
        <%= post.created_at.strftime(" %d, %B, %Y ") %>
      </p>
    </div>
<% end  %>